// <auto-generated />
using System;
using ExpenseHandler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseHandler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseHandler.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc12b61c-d4e5-4eb0-a100-00d9f1dc943e"),
                            Name = "Travel"
                        },
                        new
                        {
                            Id = new Guid("d33a33db-4d93-4221-bd56-45bc59587b0b"),
                            Name = "Meals"
                        },
                        new
                        {
                            Id = new Guid("3b7bc618-54dd-4341-8968-891229413753"),
                            Name = "Office"
                        });
                });

            modelBuilder.Entity("ExpenseHandler.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5de35a77-07f6-4e0d-b1f8-afe9374ab529"),
                            Email = "Tharun@company.com",
                            Name = "Tharun Manager"
                        },
                        new
                        {
                            Id = new Guid("ae0a2f73-8240-41c2-9d10-baa8e653e30f"),
                            Email = "Naveen@company.com",
                            ManagerId = new Guid("5de35a77-07f6-4e0d-b1f8-afe9374ab529"),
                            Name = "Naveen Employee"
                        },
                        new
                        {
                            Id = new Guid("03227966-869a-44be-8dfc-0f8f2531eee3"),
                            Email = "Pavan@company.com",
                            ManagerId = new Guid("5de35a77-07f6-4e0d-b1f8-afe9374ab529"),
                            Name = "Pavan Employee"
                        });
                });

            modelBuilder.Entity("ExpenseHandler.Entities.ExpenseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SpendDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReportId");

                    b.ToTable("ExpenseItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3691b3b5-8147-4656-8036-f7a1228e0d44"),
                            Amount = 120m,
                            CategoryId = new Guid("dc12b61c-d4e5-4eb0-a100-00d9f1dc943e"),
                            Description = "Taxi to airport",
                            ReportId = new Guid("e70be0f3-4967-4cb0-9dd5-7fcb3692f324"),
                            SpendDate = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ExpenseHandler.Entities.ExpenseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ExpenseReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e70be0f3-4967-4cb0-9dd5-7fcb3692f324"),
                            CreatedAt = new DateTime(2025, 9, 9, 17, 15, 23, 272, DateTimeKind.Utc).AddTicks(2621),
                            EmployeeId = new Guid("ae0a2f73-8240-41c2-9d10-baa8e653e30f"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ExpenseHandler.Entities.Employee", b =>
                {
                    b.HasOne("ExpenseHandler.Entities.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ExpenseHandler.Entities.ExpenseItem", b =>
                {
                    b.HasOne("ExpenseHandler.Entities.Category", "Category")
                        .WithMany("ExpenseItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpenseHandler.Entities.ExpenseReport", "Report")
                        .WithMany("Items")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ExpenseHandler.Entities.ExpenseReport", b =>
                {
                    b.HasOne("ExpenseHandler.Entities.Employee", "Employee")
                        .WithMany("ExpenseReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ExpenseHandler.Entities.Category", b =>
                {
                    b.Navigation("ExpenseItems");
                });

            modelBuilder.Entity("ExpenseHandler.Entities.Employee", b =>
                {
                    b.Navigation("ExpenseReports");
                });

            modelBuilder.Entity("ExpenseHandler.Entities.ExpenseReport", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
